### ISSUE TITLE
Errors on Step 2 and 3

### ISSUE THREAD

**Issue by exist2021** [saarthdeshpande/book-summarizer#14]
Ok, I am getting errors. Let me know what I can do. Thank you! 

![errors](https://user-images.githubusercontent.com/83490199/218040601-729d709b-b928-4623-a7fc-0795924eab59.png)

**Comment by saarthdeshpande** [comment]
1. You don't have python-pip python3-pip installed on your machine. Try pip3 instead of pip. If neither works, install pip.

2. <path-to-PDF-file> refers to the PDF file you want to summarize. Actually pass the location of the PDF file here.
