### ISSUE TITLE
importation error

### ISSUE THREAD

**Issue by Arinze1020** [saarthdeshpande/book-summarizer#5]
ImportError:
T5Tokenizer requires the SentencePiece library but it was not found in your environment. Checkout the instructions on the
installation page of its repo: https://github.com/google/sentencepiece#installation and follow the ones
that match your environment.

I have checked on the readme I didn't see anything relating to token except when you were explaining the project.

**Comment by saarthdeshpande** [comment]
Faced a similar problem post the Python3.9 release.

Solution:

Please delete your virtual environment, and create a new one using a **Python3.8** interpreter. Ensure your terminal is currently in your virtual environment and run `pip install -r requirements.txt`. 

Following this, you may run `python3 bsCLI.py --path <path-to-PDF-file>` and it works!

Closing the issue. Please let me know if this helps.
